# Generated by Django 4.1.2 on 2022-11-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mitos',
            fields=[
                ('mitoId', models.AutoField(primary_key=True, serialize=False)),
                ('Mito', models.CharField(max_length=50)),
                ('Titulo', models.CharField(max_length=120)),
                ('Dioses', models.CharField(max_length=100)),
                ('Facciones', models.CharField(max_length=50)),
                ('historia', models.CharField(max_length=1000)),
                ('Foto', models.CharField(max_length=500)),
            ],
        ),
    ]
