# Generated by Django 4.1.2 on 2022-11-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MitosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitos',
            name='Foto',
            field=models.ImageField(null=True, upload_to='ImagenMito'),
        ),
    ]
