# Generated by Django 4.1.2 on 2022-12-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MitosApp', '0002_alter_mitos_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitos',
            name='precio',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
