# Generated by Django 4.1.2 on 2023-03-19 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='mitoId',
            new_name='comentarioId',
        ),
    ]
