# Generated by Django 4.1.2 on 2023-03-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.EmailField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
