# Generated by Django 4.1.2 on 2023-03-11 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
